version: '3.8'

services:
  mainService:
    image: mainservice:latest
    ports:
      - "8080:8080"
    container_name: main_service_container
    depends_on:
      - guestBookService
      - rabbitmq
    networks:
      - app-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  guestBookService:
    image: guestbookservice:latest
    ports:
      - "8081:8081"
    container_name: guestbook_service_container
    depends_on:
      - dataBaseService
    networks:
      - app-network

  dataBaseService:
    image: databaseservice:latest
    ports:
      - "8082:8082"
    container_name: database_service_container
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
