version: '3.8'

services:
  mainService:
    image: mainservice:latest
    ports:
      - "8080:8080"
    container_name: main_service_container
    depends_on:
      - guestBookService
      - rabbitmq
    networks:
      - app-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
    volumes:
      - ./otel:/otel

  guestBookService:
    image: guestbookservice:latest
    ports:
      - "8081:8081"
    container_name: guestbook_service_container
    depends_on:
      - dataBaseService
    networks:
      - app-network
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
    volumes:
      - ./otel:/otel

  dataBaseService:
    image: databaseservice:latest
    ports:
      - "8082:8082"
    container_name: database_service_container
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
    volumes:
      - ./otel:/otel

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - app-network

  emailservice:
    image: emailservice:latest
    ports:
      - "8083:8083"
    container_name: email_service_container
    depends_on:
      - rabbitmq
    networks:
      - app-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
    volumes:
      - ./otel:/otel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.46
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
